# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20170430_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
